# Generated by Django 5.1.3 on 2024-12-22 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=100.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_classes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_class',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flights', models.ManyToManyField(related_name='bookings', to='bookings.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.passenger')),
            ],
        ),
    ]
